import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const GOOGLE_CSS =
  "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600&family=Space+Grotesk:wght@500;600;700&display=swap";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const OUT_DIR = join(process.cwd(), "src/assets/fonts");
const CSS_OUT = join(process.cwd(), "src/styles/fonts.css");

const WANTED_SUBSETS = ["U+0000-00FF", "U+0100-02BA"];

const slug = (family, weight, subset) =>
  `${family.toLowerCase().replace(/\s+/g, "-")}-${weight}-${subset}.woff2`;

const css = await fetch(GOOGLE_CSS, { headers: { "User-Agent": UA } }).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts CSS request failed: ${r.status}`);
  return r.text();
});

const blocks = css.split("@font-face").slice(1);
const kept = [];

for (const block of blocks) {
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
  const style = block.match(/font-style:\s*(\w+)/)?.[1] ?? "normal";
  const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  const range = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();

  if (!family || !weight || !url || !range) continue;
  if (!WANTED_SUBSETS.some((s) => range.includes(s))) continue;

  const subset = range.includes("U+0100-02BA") ? "latin-ext" : "latin";
  kept.push({ family, weight, style, url, range, file: slug(family, weight, subset) });
}

await mkdir(OUT_DIR, { recursive: true });

for (const face of kept) {
  const buf = await fetch(face.url, { headers: { "User-Agent": UA } }).then((r) => {
    if (!r.ok) throw new Error(`Font download failed (${r.status}): ${face.url}`);
    return r.arrayBuffer();
  });
  await writeFile(join(OUT_DIR, face.file), Buffer.from(buf));
  console.log(`  ${face.file}  ${(buf.byteLength / 1024).toFixed(1)} kB`);
}

const stylesheet = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.
   Self-hosted so no visitor request ever reaches fonts.googleapis.com. */

${kept
  .map(
    (f) => `@font-face {
  font-family: "${f.family}";
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url("../assets/fonts/${f.file}") format("woff2");
  unicode-range: ${f.range};
}`
  )
  .join("\n\n")}
`;

await writeFile(CSS_OUT, stylesheet);
console.log(`\n${kept.length} faces written to src/styles/fonts.css`);
